# The libraries in this file are used exclusively by the convention plugins

[versions]

[libraries]

gradlePlugin-android                      = { module = "com.android.tools.build:gradle", version = "7.4.0" }
gradlePlugin-kotlin                       = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version = "1.8.20" }
gradlePlugin-kotlinSerialization          = { module = "org.jetbrains.kotlin:kotlin-serialization", version = "1.8.20" }
gradlePlugin-kotlinCompose                = { module = "org.jetbrains.compose:compose-gradle-plugin", version = "1.4.0" }
gradlePlugin-ktlint                       = { module = "org.jlleitschuh.gradle:ktlint-gradle", version = "11.3.1" }
gradlePlugin-kotest                       = { module = "io.kotest:kotest-framework-multiplatform-plugin-gradle", version = "5.5.4" }
gradlePlugin-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version = "0.13.0" }
gradlePlugin-orchid                       = { module = "gradle.plugin.com.eden:orchidPlugin", version = "0.21.1" }
gradlePlugin-buildConfig                  = { module = "com.github.gmazzo:gradle-buildconfig-plugin", version = "3.1.0" }
gradlePlugin-mokoResources                = { module = "dev.icerock.moko:resources-generator", version = "0.22.0" }
gradlePlugin-sqldelight                   = { module = "com.squareup.sqldelight:gradle-plugin", version = "1.5.4" }

gradlePlugin-jetbrainsIntelliJ            = { module = "org.jetbrains.intellij.plugins:gradle-intellij-plugin", version = "1.13.3" }
gradlePlugin-jetbrainsChangelog           = { module = "org.jetbrains.intellij.plugins:gradle-changelog-plugin", version = "2.0.0" }

okhttp                                    = { module = "com.squareup.okhttp3:okhttp", version = "4.10.0" }
semver                                    = { module = "net.swiftzer.semver:semver", version = "1.1.2" }
